### PR TITLE
Allow to configure test repo url and branch

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
/packit-stg test --labels smoke --env TEST_REPO_URL=https://github.com/streamshub/streams-e2e.git --env TEST_REPO_BRANCH=rocks-db-test

**Comment by kornys** [comment]
/packit-dev test --labels smoke --env TEST_REPO_URL=https://github.com/streamshub/streams-e2e.git --env TEST_REPO_BRANCH=rocks-db-test

**Comment by kornys** [comment]
/packit-stg test --labels smoke --env TEST_REPO_URL=https://github.com/streamshub/streams-e2e.git --env TEST_REPO_BRANCH=rocks-db-test

**Comment by kornys** [comment]
works with packit-stg, for working with prod packit we need to wait until Monday with merge this PR

**Review by Frawless — APPROVED** [review]

**Pull request merged**
